source "https://rubygems.org/"

# App Stack
gem "sinatra"
gem "slim"
gem "i18n"
gem "sinatra-contrib"


group :development do
  gem "rake", "~> 10.0"
  gem "minitest", "~> 5.2"
  gem "rack-test", "~> 0.6"
end
