-
  link: http://www.meetup.com/fr-FR/parisrb/
  img: news/parisrb.png
  title: Paris.rb
  date_t: parisrb_1_date
  desc_t: parisrb_1_desc_html
-
  link: https://www.facebook.com/events/1678846872385676/
  img: news/hopdrink-janvier.png
  title: Hopdrinks
  date_t: hopdrinks_date
  desc_t: hopdrinks_desc_html
-
  link: http://www.meetup.com/fr-FR/parisrb/
  img: news/parisrb.png
  title: Paris.rb
  date_t: parisrb_2_date
  desc_t: parisrb_2_desc_html
