# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_password: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: example.com
  secret_key_base: 03ef9252411352d3b6123d5272ec2f6ce2178eb3147158394337138c07a961a0233ef660ccb3dc987c3f1789204736f26fdbaa827b67b1592757dc51d2ce3f6

test:
  domain_name: example.com
  secret_key_base: fefc5652e5758f5a8548fee03452799c36288796649f98076e469cedeeaf827de5bdcf29cd1c7377188d81cfe217f02654fd8bc7a6b724f66fe290dc080552d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_password: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>